version: '3.7'
services:
  db:
    image: mysql:5.7
    ports:
      - "13306:3306"
    restart: always
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
      MYSQL_DATABASE: sample
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql

  application:
    build: ./server-side
    environment:
      MYSQL_DATABASE: myadmin
      MYSQL_HOST: db
      MYSQL_PASSWORD: password
      MYSQL_PORT: 3306
      MYSQL_USER: root
    depends_on:
      - db
    ports:
      - "8010:8080"
    restart: always
    volumes:
      - ./server-side:/app

volumes:
  mysql-data:
    driver: local
